//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Entity;
namespace Weather.Model
{
    public partial class Air_Quality_Types  
    {
        public int Air_Quality_Type_Id { get; set; }
        public string Description { get; set; }
        public int Start { get; set; }
        public int End { get; set; }
    }
    
}
