//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Entity;
namespace Weather.Model
{
    public partial class Spatial  
    {
        public Spatial() 
        {
            this.Location_Aware_Message = new HashSet<Location_Aware_Message>();
            this.Weathers = new HashSet<Weather>();
        }
    
        public int Spatial_Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
    
        public virtual ICollection<Location_Aware_Message> Location_Aware_Message { get; set; }
        public virtual ICollection<Weather> Weathers { get; set; }
    }
    
}
