//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Entity;
namespace Weather.Model
{
    public partial class Weather  
    {
        public int Weather_Id { get; set; }
        public int Spatial_Id { get; set; }
        public Nullable<double> Temperature { get; set; }
        public double Temperature_Feels { get; set; }
        public int Weather_Type_Id { get; set; }
        public Nullable<int> Wind_Speed { get; set; }
        public Nullable<int> Wind_Direction_Id { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<int> Air_Quality_Num { get; set; }
    
        public virtual Spatial Spatial { get; set; }
        public virtual Weather_Types Weather_Types { get; set; }
        public virtual Wind_Directions Wind_Directions { get; set; }
    }
    
}
