//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Entity;
namespace Weather.Model
{
    public partial class Weather_Types  
    {
        public Weather_Types() 
        {
            this.Weathers = new HashSet<Weather>();
        }
    
        public int Weather_Type_Id { get; set; }
        public string Weather_Type { get; set; }
    
        public virtual ICollection<Weather> Weathers { get; set; }
    }
    
}
