//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Entity;
namespace Weather.Model
{
    public partial class Wind_Levels  
    {
        public int Wind_Level_Id { get; set; }
        public string Level { get; set; }
        public Nullable<int> Speed_Start { get; set; }
        public Nullable<int> Speed_End { get; set; }
    }
    
}
