#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Weather.Andriod.Resource", IsApplication=true)]

namespace Weather.Andriod
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_notitlebar_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Cloudy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int microsoft = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Rainy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Sunny = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int InnerRelativeLayout = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int condSection = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int dcTime = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int imageMS = 2131165203;
			
			// aapt resource value: 0x7f070009
			public const int imgWeatherType = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int longSection = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int tempSection = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int tvAirQualityInfo = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int tvAirQualityNum = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int tvAsOf = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int tvFeelLike = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int tvHumidityInfo = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int tvHumidityTitle = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int tvLocation = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int tvTemperature = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int tvTimeZone = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int tvWeatherType = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int tvWelcomeInfo = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int tvWindInfo = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int tvWindTitle = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int WeatherServiceLoc = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
