//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Aware_Message
    {
        public int Message_Id { get; set; }
        public int Spatial_Id { get; set; }
        public string Message { get; set; }
    
        public virtual Spatial Spatial { get; set; }
    }
}
