//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherEntities : DbContext
    {
        public WeatherEntities()
                : base(DbConnUtility.BuildEFConnectionString(typeof(WeatherEntities), "Weather")) //: base("name=WeatherEntities") 
    
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Air_Quality_Types> Air_Quality_Types { get; set; }
        public virtual DbSet<Location_Aware_Message> Location_Aware_Message { get; set; }
        public virtual DbSet<Spatial> Spatials { get; set; }
        public virtual DbSet<Weather> Weathers { get; set; }
        public virtual DbSet<Weather_Types> Weather_Types { get; set; }
        public virtual DbSet<Wind_Directions> Wind_Directions { get; set; }
        public virtual DbSet<Wind_Levels> Wind_Levels { get; set; }
    }
}
